### ISSUE TITLE
Termination of Endless Loop in CCS Editor

### ISSUE THREAD

**Issue by pasetti** [mmecina/CCS#10]
In the CCS editor, I need to have a loop where the same telecommand is sent cyclically. I implement it through the following python code:
```
import time
while True:
    cfl.Tcsend_DB('TC_TEST_CONNECT', pool_name='LIVE')
    time.sleep(2)
```
This works as expected but how do I stop the loop? I have tried CTRL-C and CTRL-D in both the editor but neither works. Is there some other way of stopping a running loop?

**Comment by mmecina** [comment]
CTRL-C is caught by the text editor for copy-paste. To interrrupt a running command in the IPython console press CTRL+SHIFT+C.

**Comment by pasetti** [comment]
I have added a note as per clarification provided by Marko in CoCa's ReadMe file.
