### ISSUE TITLE
Automatic Scrolling Disabled in PoolViewer

### ISSUE THREAD

**Issue by pasetti** [mmecina/CCS#13]
When I run a test, I look at the results in the PoolViewer. Initially, the window with the incoming TM packets scrolls automatically (i.e. I always see the latest TM packet in the last line at the bottom of the display window). If, however, I select a TM packet to inspect its content, I then find that the automatic scrolling of the display window has been disabled and, if I want to see the most recent TM packets, I must manually scroll to the end.

Is there any way to re-enable automatic scrolling?

**Comment by mmecina** [comment]
Pressing the END key jumps to the last received packet and re-enables automatic scrolling.

**Comment by pasetti** [comment]
Thanks. I tried it and it works.
