### ISSUE TITLE
Row Limits in Plots

### ISSUE THREAD

**Issue by pasetti** [mmecina/CCS#16]
When I use the plotting tool, I have the option to set the maximum and minimum values for the X- and Y-axes. This is obviously helpful but there is another common need which, as far as I can tell, is currently not covered: I would like to only consider measurements in a given range of rows. This is typically the case where the instrument had a reset and the instrument time was reset. This sometimes results in the same range of time values being present twice in the tmpool and this in turns result in ugly plots. If I could specified a RowMin and RowMax, I would be able to only select ranges of tmpool rows with monotonically increasing instrument times.

**Comment by mmecina** [comment]
This functionality is already available. In the toolbar at the top of the plotting window there are two entry fields ("MIN" & "MAX") which take the row indices ("'#" column in the Poolviewer) to set RowMin and RowMax, respectively. When values are entered, already plotted data will not be updated, but the range will be applied to any parameters plotted after.

**Comment by pasetti** [comment]
Thanks, Marko. I have tried this and it works very well!
