### ISSUE TITLE
Handling of Database Errors When Importing MIB Tables

### ISSUE THREAD

**Issue by pasetti** [mmecina/CCS#6]
I am importing the MIB Tables for my project and I find that the import process fails because of an inconsistency between the structure of a MIB Table and its description in file `Ccs/tools/scos2000db.json`. The error results in an exception and in the import script being aborted. This is inconvenient because I would like to see all inconsistencies which are present in my MIB Tables. I have therefore made a simple change in script Ccs/tools/import_mib.py such that, when the script encounters an error, it reports it but then continues processing the remaining table. The modified script has been pushed on the CoCa branch of the CCS project.

The purpose of this ticket is to flag this change to Marko in case he wishes to take it over for the main project branch.

**Comment by mmecina** [comment]
I have added an `--ignore` option to `import_mib.py` that lets the import continue in case a table fails.
